# Generated by Django 4.1.1 on 2023-05-01 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('p_pk_id', models.AutoField(primary_key=True, serialize=False, verbose_name='기본키(자동 증가)')),
                ('p_category', models.CharField(choices=[('A', 'TYPE A'), ('B', 'TYPE B'), ('C', 'TYPE C'), ('D', 'TYPE D')], default='A', max_length=10, verbose_name='상품 카테고리 종류')),
                ('p_price', models.IntegerField(default=0, verbose_name='상품 가격')),
                ('p_cost', models.IntegerField(default=0, verbose_name='상품 원가')),
                ('p_name', models.CharField(default='', max_length=128, verbose_name='상품 이름')),
                ('p_subscription', models.CharField(default='', max_length=128, verbose_name='상품 이름')),
                ('p_barcode', models.CharField(default='', max_length=128, verbose_name='상품 이름')),
                ('p_expire_date', models.CharField(default='', max_length=128, verbose_name='상품 이름')),
                ('p_size', models.CharField(choices=[('S', 'small'), ('L', 'large')], default='S', max_length=16, verbose_name='상품 사이즈')),
                ('p_delete_check', models.BooleanField(default=False, verbose_name='상품 삭제 여부')),
                ('p_regi_user', models.CharField(default='', max_length=128, verbose_name='로그인 아이디')),
                ('p_regi_date', models.DateTimeField(auto_now_add=True, verbose_name='최초 가입 날짜')),
                ('p_fix_date', models.DateTimeField(auto_now_add=True, verbose_name='상품 정보 수정 날짜')),
                ('p_keyword', models.CharField(default='', max_length=128, verbose_name='상품 초성 키워드')),
            ],
        ),
    ]
