FROM python:3.9
ENV TZ=Asia/Seoul
ENV PYTHONUNBUFFERED 1

# RUN python -m pip install --upgrade pip
RUN mkdir /backend
WORKDIR /backend
ADD /py3_lib/requirements.txt .
RUN pip install -r requirements.txt