# Generated by Django 4.1.1 on 2023-05-15 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('profile_pk_id', models.AutoField(primary_key=True, serialize=False, verbose_name='기본키(자동 증가)')),
                ('user_id', models.CharField(default='', max_length=64, verbose_name='유저 ID (휴대폰 번호 사용)')),
                ('user_pw', models.CharField(default='', max_length=256, verbose_name='유저 PW (암호화 저장 - 단방향 해시)')),
                ('phone_num', models.CharField(default='', max_length=30, verbose_name='유저 휴대폰 번호 : 유저 ID와 동일하게 사용')),
                ('last_login', models.DateTimeField(null=True, verbose_name='마지막 로그인 날짜')),
                ('regi_date', models.DateTimeField(auto_now_add=True, verbose_name='최초 가입 날짜')),
            ],
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('token_pk_id', models.AutoField(primary_key=True, serialize=False, verbose_name='기본키(자동 증가)')),
                ('refresh_token', models.CharField(default='', max_length=256, verbose_name='유저에게 발급된 rfresh_token 저장')),
                ('relation_id', models.OneToOneField(db_column='relation_id', on_delete=django.db.models.deletion.CASCADE, to='auth_app.profile')),
            ],
        ),
    ]
